#!/usr/bin/with-contenv bash
set -e
source $BITNAMI_PREFIX/bitnami-utils.sh

# remove initialization commands from last run
rm -rf /tmp/init_mysql.sql

if [ ! "$(ls -A $BITNAMI_APP_VOL_PREFIX/conf)" ]; then
  generate_conf_files
fi

if [ ! -d $BITNAMI_APP_VOL_PREFIX/data/mysql ]; then

  initialize_database

  create_custom_database

  create_mysql_user

  configure_replication

  print_app_credentials $BITNAMI_APP_NAME $MARIADB_USER `print_mysql_password` `print_mysql_database`
else
  print_container_already_initialized $BITNAMI_APP_NAME
fi

# Look for SQL files to import in /docker-entrypoint-initdb.d/
for f in /docker-entrypoint-initdb.d/*; do
	case "$f" in
		*.sh)     echo "$0: running $f"; . "$f" ;;
		*.sql)    echo "$0: running $f"; "${mysql[@]}" < "$f"; echo ;;
		*.sql.gz) echo "$0: running $f"; gunzip -c "$f" | "${mysql[@]}"; echo ;;
		*)        echo "$0: ignoring $f" ;;
	esac
	echo
done

chown -R $BITNAMI_APP_USER:$BITNAMI_APP_USER \
  $BITNAMI_APP_VOL_PREFIX/conf/ \
  $BITNAMI_APP_VOL_PREFIX/logs/ \
  $BITNAMI_APP_VOL_PREFIX/data/ || true


